### ISSUE TITLE
File Size

### ISSUE THREAD

**Issue by Coolaction77** [SurvivCreator/Battlefront-Redux#4]
Files are starting to be too big

**Comment by Coolaction77** [comment]
I attempted to upload version v0.5, I believe, and it said it had to be less than 25 mb, and v0.5 is already 44 mb. We could upload them separately, maybe, but this will likely be a recurring problem.

**Comment by SurvivCreator** [comment]
We can fix that by packaging it thru the packager.github.io as a zip output

**Comment by SurvivCreator** [comment]
Also on the topic of possibly incomplete updates, I was thinking we should make a canary version of xeno (an unstable testing ground for updates). Both Microsoft and Google have this and I think it will be beneficial for development.

A possible logo
![image](https://user-images.githubusercontent.com/88222138/135962074-eb7aaadd-bd97-4332-965f-4183a173c63b.png)

**Comment by SurvivCreator** [comment]
So we now have 
![image-removebg-preview - 2021-10-04T215639 449](https://user-images.githubusercontent.com/88222138/135962679-aed8c842-cdb0-4a54-a2b7-a52179f41c88.png)
![8355f49b4747da3cb3a3a35641933a9a-removebg-preview (1)](https://user-images.githubusercontent.com/88222138/135962682-2510688d-43e2-44de-a74b-9e79560094b0.png)

**Comment by Coolaction77** [comment]
Ok. Is there any particular reason for naming it Canary? Also I think it's a good idea, although if one of the new features just hasn't enough content or a good way to start it we probably shouldn't add it.

**Comment by SurvivCreator** [comment]
I agree. I named it Canary because it's what most companies call their alpha testing sites and whatnot.

**Comment by Coolaction77** [comment]
Ok, sounds good! (I was just wondering because I couldn't find any reference while searching)
